// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jymajpnwthgqcghmkmam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5bWFqcG53dGhncWNnaG1rbWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTU1OTYsImV4cCI6MjA2OTM3MTU5Nn0.J6dMZX-UCAS7PGCsKyamhQwTaqfBJ662HTWA8KgJCbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});